# Generated by Django 3.1.7 on 2021-04-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodaftmodel',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
