# Generated by Django 3.1.7 on 2021-04-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210401_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prodaftModel',
            new_name='userModel',
        ),
    ]
