# Generated by Django 3.1.7 on 2021-04-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20210402_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.TextField(max_length=30),
        ),
    ]
